---
version: "3"
services:
  central-acesso:
    container_name: central-acesso
    build: .
    ports:
      - 4000:4000
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - backend

networks:
  backend:

volumes:
  esdata1:
